Chapter 3
alexVOLTS/Study pull request #3
Opened 2022-08-01 20:14 UTC by alexVOLTS

2022-08-02 16:31 UTC, dimmykar requested changes
Good work! But you have some nitpicks

2022-08-02 16:31 UTC, dimmykar commented on Chapter_3/2.c
> +    getchar();
Why does the function call twice? First time to stop program until the key pressed and what about the second?

2022-08-02 16:31 UTC, dimmykar commented on Chapter_3/5.c
> +    int sec = year*3.156E7;
Also use the define or const variable for magic number `3.156E7`

2022-08-02 16:31 UTC, dimmykar commented on Chapter_3/6.c
> +    float molecul = 3.0E-23;
If this is constant value, then you need to use const variable

```c
const float molecul = 3.0E-23;
```

2022-08-02 16:31 UTC, dimmykar commented on Chapter_3/7.c
> +        if (cm > 180)
Magic number `180`

2022-08-10 20:23 UTC, dimmykar requested changes

2022-08-10 20:23 UTC, dimmykar commented on Chapter_3/7.c
> +    float cm = height * 2.54;
Magic number, use define, please

2022-08-23 18:02 UTC, alexVOLTS commented on Chapter_3/3.c
> +    printf ("\a Напуганная внезапным звуком, Вика вскрикнула: \n \"Во имя всех звезд, что это было!\""); // \a - предупредительный звук (стандарт ANSI C)
Yeah it is LOL

2022-08-23 18:33 UTC, alexVOLTS commented on Chapter_3/2.c
> +    getchar();
Have no idea, found that form in the internet. Will fix this soon

2022-08-25 18:15 UTC, dimmykar commented on Chapter_3/6.c
> +#define MOLECUL    3.0E-23f
It will be `0.0000` for `float`. Use `3.0E-23` instead

2022-08-25 18:17 UTC, dimmykar commented on Chapter_3/5.c
> +#define SECONDS    3.156E7f
Do not use `float` for very small values. Use `3.156E7` instead (`double`)

2022-09-03 18:05 UTC, merged