Chapter 5, task 5.9
alexVOLTS/Study pull request #5
Opened 2022-08-09 17:28 UTC by alexVOLTS

Task #5.9 is ready to check

2022-08-10 17:12 UTC, dimmykar requested changes
Good, but you need to learn how to give clearer names for defines and variables and don't forget about `void`)

2022-08-10 17:12 UTC, dimmykar commented on Chapter_5/7.c
> +int calculate ()
bleat'

2022-08-10 17:12 UTC, dimmykar commented on Chapter_5/7.c
> +int main (void)
ditto

2022-08-10 17:12 UTC, dimmykar commented on Chapter_5/8.c
> +int cycle (void)
remove space, please

2022-08-10 17:12 UTC, dimmykar commented on Chapter_5/9.c
> +int Temperatures()
Missed `void`

2022-08-10 17:12 UTC, dimmykar commented on Chapter_5/9.c
> +int Input ()
ditto

2022-08-10 17:12 UTC, dimmykar commented on Chapter_5/9.c
> +int main ()
ditto

2022-08-23 18:48 UTC, alexVOLTS commented on Chapter_5/1.c
> +        printf("\nTime in hourse and minutes: %d hours %.0f minutes", a, c);
LOL my mistake

2022-08-23 18:49 UTC, alexVOLTS commented on Chapter_5/2.c
> +    }
Nice! Will note this one

2022-08-23 18:53 UTC, alexVOLTS commented on Chapter_5/4.c
> +int input()
OK :D

2022-09-03 18:08 UTC, merged