Lessons
alexVOLTS/Study pull request #6
Opened 2022-08-12 14:46 UTC by alexVOLTS

Tasks from our lessons

2022-08-23 12:28 UTC, dimmykar requested changes
Good! I leave some comments in your code

2022-08-23 12:28 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_2.c
> +    char y[13][3] = {"M","CM","D","CD","C","XC","L","XL","X","IX","V","IV","I"};
Why do you use two-dimensional array?

2022-08-23 12:28 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_2.c
> +    }
This check should be done on line 18-19 (before the main algorithm's loop). If `0` is entered, why do you perform the conversion?

2022-08-23 12:28 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_2.c
> +    return 0;
Why you return the value `0`? You return the `0` value on fail in other cases, but if you reach this line, then your conversion is successful. You neen to return `1` in this case or it is better to use `bool` as returning type

2022-08-23 12:28 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_2.c
> +    int number = z;
I don't see any reason to use the `number` variable if you move the check to `0` before the conversion loop

2022-08-23 12:28 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_2.c
> +        printf("\nNumber must be in a range 0 - 3999");
`Number must be in a range 1...3999`

2022-08-23 12:28 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_3.c
> +#include <float.h>
ditto

2022-08-23 12:28 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_3.c
> +    if (a == 'M') return 1000;
It is better to use `switch` statement

```c
switch (a) {
  case 'I': return 1;
  ...
  default: return -1;
}
```

2022-08-23 12:28 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_3.c
> +int converter(char number[])
This notation is correct, but rarely used by programmers. Most often you will see the following similar line

```c
int converter(char *number)
```

2022-08-23 12:28 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_3.c
> +                result = result + symbol_2 - symbol_1;
`result += symbol_2 - symbol_1;`

2022-08-23 12:28 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_3.c
> +                result = result + symbol_1;
`result += symbol_1;`

2022-08-23 12:28 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_3.c
> +            result = result + 1;
`result++;`

2022-08-23 12:28 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_4.c
> +#include <locale.h>
ditto

2022-08-28 12:09 UTC, dimmykar requested changes
Not sure if exercise 1_5 works properly...((( I left a few suggestions to help rewrite it properly.

Also a bad approach to the calculation was chosen: first, you convert `20xx` input year into seconds - this is a very large number and I'm sure that there is an INTEGER OVERFLOW. Then you subtract a huge number (but it is overflowed) from this number: `2000` in seconds == `63113904000u`.

You could avoid this by immediately subtracting `20xx - 2000` and then converting the remainder to seconds

2022-08-28 12:09 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_5.c
> +                if (leap = true)
It is not comparing... it must be `if (leap == true)`

But it is better to use `if (leap)`

2022-08-28 12:09 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_5.c
> +#define     __TWO_THOUSAND          63113904000u    // Seconds in 2000 years
Be careful, because `63113904000u` > `UINT_MAX_VALUE` (`2147483647`)

2022-08-28 12:09 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_5.c
> +#define     __HOUR_TO_SEC           3600u           // Hour to seconds
It is bad practice to use `__` prefix for defines. Usually it is used for macros `__MACRO()`

2022-08-28 13:35 UTC, alexVOLTS commented on Lesson#1/Tasks/Lesson#1_3.c
> +    if (a == 'M') return 1000;
Yes, I know, but I haven't used it yet. Need to practise it on this Task :)

2022-08-30 17:41 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_2.c
> +    }
This code will never run due to the condition above

2022-08-30 18:25 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_3.c
> +    scanf("%s", &number);
`&number` is `char**`, but you need to pass `char*`

2022-08-30 18:26 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_3.c
> +    int value = 0;
Unused variable

2022-09-08 07:59 UTC, dimmykar requested changes

2022-09-08 07:59 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_5.c
> +    bool leap;
Why do you declare this variable? You don't use it in `main()` function, you use it just because you develop the `calculate_month()` function with `leap` pointer. You can deprecate this variable and rewrite `calculate_month()` function without `leap` pointer. Please, do this

2022-09-08 07:59 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_5.c
> +void calculate_month(int month, int *sec_month, bool *leap)
I don't see the reason to use `leap` pointer. It use only inside this function, not outside. Use the local variable `bool leap` instead. Make simple APIs (functions)

2022-09-08 07:59 UTC, dimmykar commented on Lesson#1/Tasks/Lesson#1_5.c
> +            if ((*leap) = true) {
Bug. It is not comparing. Because of this, this `if` statement always `true`. Here MUST be

`if ((*leap) == true) { ... }`

and I advice to use this construction for `bool`s

`if ((*loop)) { ... }` instead

2022-10-18 08:47 UTC, dimmykar commented on Programs/CAR/car/engine.c
> +int engine_get_temperature(void)
The problem with this function is that it does not return the temperature of a specific engine according to it's name. You can change the function name to `engine_get_default_temperature()` and change nothing in body, or change the body of the function to

```c
int engine_get_temperature(struct engine *engine_ptr)
{
     return engine_ptr->temp;
}
```

2022-10-18 08:47 UTC, dimmykar commented on Programs/CAR/car/car.c
> +int fuel_volume_buy, fuel_volume_drain, eng_temp;
You can use this variables in corresponding functions. And `eng_temp` is not used, so you can delete it

2022-10-20 17:07 UTC, dimmykar commented on Programs/CAR/car/engine.c
> +	engine_ptr->temp = ENGINE_DEFAULT_TEMP;
Ok, so be it. We will assume that this function is a stub that will be rewritten properly in future. However, "getters" should not set the fields they return. This should be done by the appropriate "setters"!

2022-10-20 17:07 UTC, dimmykar commented on Programs/CAR/main.c
> +				printf("\n\nEngine temperature is %d degrees Celsius", car_ptr->eng_ptr->temp);
As I said above, this code works because the "getter" internally sets the `temp` field and returns it. In theory, the "getter" should **ONLY** return the corresponding field of the object, then it makes more sense to rewrite it with the following code:

```c
printf("\n\nEngine temperature is %d degrees Celsius", engine_get_temperature(car_ptr->eng_ptr));
```

instead of

```c
engine_get_temperature(car_ptr->eng_ptr);
printf("\n\nEngine temperature is %d degrees Celsius", car_ptr->eng_ptr->temp);
```

2022-12-29 06:22 UTC, dimmykar commented
You can merge this request, delete branch and push lessons to master. The PRs is used for small code reviews, but this PR is too big for review

2022-12-29 06:23 UTC, dimmykar approved these changes

2022-12-29 11:19 UTC, merged